name: news_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  hydrated_bloc: ^9.1.4
  intl: ^0.18.1
  logger: ^2.1.0
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  url_strategy: ^0.2.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_flavorizr: ^2.2.2
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/flags/

flutter_gen:
  output: lib/generated/
  assets:
    outputs:
      style: camel-case
  integrations:
    flutter_svg: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    production:
      app:
        name: "News App"
      android:
        applicationId: "com.abdallah.news_app"
      ios:
        bundleId: "com.abdallah.news_app"

    dev:
      app:
        name: "News App Dev"
      android:
        applicationId: "com.abdallah.news_app.dev"
      ios:
        bundleId: "com.abdallah.news_app.dev"

    mock:
      app:
        name: "News App Mock"
      android:
        applicationId: "com.abdallah.news_app.mock"
      ios:
        bundleId: "com.abdallah.news_app.mock"
