name: build

on:
  pull_request:
    branches:
      - dev

jobs:
  analyze:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path

      - name: Clean
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format lib test --set-exit-if-changed

      - name: Analyze
        run: flutter analyze lib test

      - name: Test
        run: flutter test --coverage

      - name: Build
        run: flutter build appbundle --release --flavor dev --target lib/main_dev.dart
